### ISSUE TITLE
update AA Marketo integration

### ISSUE THREAD

**Issue by jsoohoo2** [AdobeDocs/contributor.en#36]
Issue in ./help/introduction.md

My client who licenses both AA and Marketo criticized this doc as 
1.  Being out of date, including screenshots and last updated.   Is RTP still an active Marketo feature?
2.  The integration focuses on activation and not insights, which is Analytics primary focus.  Can someone make that crystal clear so end users understand the docs purpose.  Add any Analytics Workspace integration links or instructions.

**Comment by jsoohoo2** [comment]
sorry, thought it was referenced in this issue already.

See:
https://experienceleague.adobe.com/docs/marketo/using/product-docs/web-personalization/reporting-for-web-personalization/web-analytics-integrations/integrate-with-adobe-analytics.html?lang=en

**Comment by bbringhu** [comment]
Thanks. I copied it over and sent a message to Keith.
